'use strict';

let calculation = document.getElementById('start'),
  incomeButton = document.getElementsByTagName('button')[0],
  expensesButton = document.getElementsByTagName('button')[1],
  depositCheck = document.querySelector('#deposit-check'),
  additionalIncomeItem = document.querySelectorAll('.additional_income-item'),
  value = document.getElementsByClassName('result-total'),
  budgetMonthValue = value[0],
  budgetDayValue = value[1],
  expensesMonthValue = value[2],
  additionalIncomehValue = value[3],
  additionalExpensesValue = value[4],
  incomePeriodValue = value[5],
  targetMonthValue = value[6],
  salaryAmount = document.querySelector('.salary-amount'),
  incomeTitle = document.querySelector('.income-title'),
  incomeAmount = document.querySelector('.income-amount'),
  additionalIncomeItem1 = document.querySelectorAll('.additional_income-item')[0],
  additionalIncomeItem2 = document.querySelectorAll('.additional_income-item')[1],
  expensesTitle = document.querySelector('.expenses-title'),
  expensesAmount = document.querySelector('.expenses-amount'),
  targetAmount = document.querySelector('.target-amount'),
  periodRange = document.querySelector('[type="range"]');